# Generated by Django 5.1.4 on 2024-12-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificado', '0002_auto_20241211_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedente', models.CharField(max_length=255)),
                ('cesionario', models.CharField(max_length=255)),
                ('fecha_cesion', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('terminado', 'Terminado')], default='terminado', max_length=255),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='fecha_terminacion_prorrogas',
            field=models.DateField(blank=True, default='2024-12-31', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='plazo_total_ejecucion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='suspensiones',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cesion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificado.cesion'),
        ),
    ]
